default: apply

apply: init fmt validate
    terraform apply -auto-approve

init:
    terraform init

fmt:
    terraform fmt

validate:
    terraform validate

destroy:
 terraform destroy

graph:
    terraform graph -type=plan | dot -Tpng >../docs/tf.png
