apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jetstack-paul
  name: certmanagerkcc
spec:
  title: Cert Manager
  permissions:
    - dns.resourceRecordSets.create
    - dns.resourceRecordSets.list
    - dns.resourceRecordSets.get
    - dns.resourceRecordSets.update
    - dns.resourceRecordSets.delete
    - dns.changes.get
    - dns.changes.create
    - dns.changes.list
    - dns.managedZones.list
  stage: GA
