apiVersion: v1
kind: Namespace
metadata:
  name: my-kcc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-ksa
  namespace: my-kcc
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gke-wif-kcc
  namespace: my-kcc
spec:
  member: principal://iam.googleapis.com/projects/993897508389/locations/global/workloadIdentityPools/jetstack-paul.svc.id.goog/subject/ns/my-kcc/sa/my-ksa
  role: roles/storage.objectViewer
  resourceRef:
    kind: Project
    external: projects/jetstack-paul
  # condition:
  #   expression: 'resource.type=="container.googleapis.com/Clusters" && resource.name.startsWith("projects/jetstack-paul/zones/europe-west2-a/clusters/example")'
  #   title: gke-wif-kcc
