apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: my-kcc
spec:
  serviceAccountName: my-ksa
  containers:
  - name: test-pod
    image: google/cloud-sdk:slim
    command: ["sleep","infinity"]
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
